services:
    form.helper.error:
        class: FormHelper\ErrorBundle\Helper\FormErrorHelper
        public: true
        arguments: ["@translator.default"]
        calls:
            - [setFormFactory, ["@form.factory"]]
